version: "3.7"

services:
  api:
    build: .
    image: ${API_NAME}:${API_VERSION}
    container_name: ${API_NAME}
    env_file: .env
    restart: always
    ports:
      - "${API_PORT}:${API_PORT}"
    volumes:
      - .:/home/node/api
    networks:
      - api
      - services
    depends_on:
      - nginx
      - redis
      - mongo

  redis:
    image: redis:${REDIS_VERSION}
    container_name: redis-${API_NAME}
    restart: always
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - redis:/data
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - REDIS_PASSWORD=${REDIS_PASS}
    networks:
      - services

  redis_workbench:
    image: redislabs/redisinsight
    container_name: redis_workbench-${API_NAME}
    restart: always
    ports:
      - "${REDIS_WORKBENCH_PORT}:${REDIS_WORKBENCH_PORT}"
    networks:
      - services
    depends_on:
      - redis

  mongo:
    image: mongo:${MONGO_VERSION}
    container_name: mongo-${API_NAME}
    restart: always
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    volumes:
      - "mongo:/data/db"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASS}
    networks:
      - services

  nginx:
    image: nginx:${NGINX_VERSION}
    container_name: nginx-${API_NAME}
    restart: always
    ports:
      - "${NGINX_HTTP_PORT}:${NGINX_HTTP_PORT}"
      - "${NGINX_HTTPS_PORT}:${NGINX_HTTPS_PORT}"
    volumes:
      - "nginx:/var/www/html"
      - "nginx:/var/log/nginx"
      - "./nginx.conf:/etc/nginx/conf.d/nginx.conf"
    networks:
      - jsm
      - api

volumes:
  mongo:
    name: mongo
  redis:
    name: redis
  nginx:
    name: nginx

networks:
  jsm:
    name: jsm
    driver: bridge
  api:
    name: jsm-api
    driver: bridge
  services:
    name: jsm-services
    driver: bridge
